# Generated by Django 3.1.6 on 2021-02-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQuestionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('asked_question_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
