# Generated by Django 3.1.6 on 2021-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotweb', '0002_scrapercookiecatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapercookiecatcher',
            name='website_domain',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
