# Generated by Django 3.1.6 on 2021-02-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotweb', '0002_chatbotquestionsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotquestionsession',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbotweb.user'),
        ),
    ]
