# Generated by Django 3.1.6 on 2021-02-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotweb', '0003_auto_20210214_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotquestionsession',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userpersonality',
            old_name='user_id',
            new_name='user',
        ),
    ]
