# Generated by Django 3.1.6 on 2021-02-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotweb', '0004_auto_20210214_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquestionsession',
            name='question_key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
