# Generated by Django 3.1.6 on 2021-02-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotweb', '0005_chatbotquestionsession_question_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(verbose_name='date published')),
                ('finishing_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbotweb.user')),
            ],
        ),
    ]
