# Generated by Django 3.1.6 on 2021-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotweb', '0007_auto_20210216_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_key', models.CharField(max_length=200)),
                ('personality_value', models.CharField(max_length=200)),
            ],
        ),
    ]
